# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kullanicikayit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblID = QtWidgets.QLabel(self.centralwidget)
        self.lblID.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.lblID.setObjectName("lblID")
        self.lblNAME = QtWidgets.QLabel(self.centralwidget)
        self.lblNAME.setGeometry(QtCore.QRect(10, 60, 61, 21))
        self.lblNAME.setObjectName("lblNAME")
        self.lblNUMBER = QtWidgets.QLabel(self.centralwidget)
        self.lblNUMBER.setGeometry(QtCore.QRect(10, 140, 61, 21))
        self.lblNUMBER.setObjectName("lblNUMBER")
        self.lblMAIL = QtWidgets.QLabel(self.centralwidget)
        self.lblMAIL.setGeometry(QtCore.QRect(10, 180, 61, 21))
        self.lblMAIL.setObjectName("lblMAIL")
        self.lblCITY = QtWidgets.QLabel(self.centralwidget)
        self.lblCITY.setGeometry(QtCore.QRect(10, 220, 61, 21))
        self.lblCITY.setObjectName("lblCITY")
        self.lblSURNAME = QtWidgets.QLabel(self.centralwidget)
        self.lblSURNAME.setGeometry(QtCore.QRect(10, 100, 61, 21))
        self.lblSURNAME.setObjectName("lblSURNAME")
        self.txtID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtID.setGeometry(QtCore.QRect(70, 20, 113, 21))
        self.txtID.setObjectName("txtID")
        self.txtNAME = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNAME.setGeometry(QtCore.QRect(70, 60, 113, 21))
        self.txtNAME.setObjectName("txtNAME")
        self.txtSURNAME = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSURNAME.setGeometry(QtCore.QRect(70, 100, 113, 21))
        self.txtSURNAME.setObjectName("txtSURNAME")
        self.txtMAIL = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMAIL.setGeometry(QtCore.QRect(70, 180, 113, 21))
        self.txtMAIL.setObjectName("txtMAIL")
        self.txtCITY = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCITY.setGeometry(QtCore.QRect(70, 220, 113, 21))
        self.txtCITY.setObjectName("txtCITY")
        self.txtNUMBER = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNUMBER.setGeometry(QtCore.QRect(70, 140, 113, 21))
        self.txtNUMBER.setObjectName("txtNUMBER")
        self.btnSAVE = QtWidgets.QPushButton(self.centralwidget)
        self.btnSAVE.setGeometry(QtCore.QRect(570, 10, 201, 51))
        self.btnSAVE.setObjectName("btnSAVE")
        self.btnDELETE = QtWidgets.QPushButton(self.centralwidget)
        self.btnDELETE.setGeometry(QtCore.QRect(570, 70, 201, 51))
        self.btnDELETE.setObjectName("btnDELETE")
        self.btnUPDATE = QtWidgets.QPushButton(self.centralwidget)
        self.btnUPDATE.setGeometry(QtCore.QRect(570, 130, 201, 51))
        self.btnUPDATE.setObjectName("btnUPDATE")
        self.tblLISTED = QtWidgets.QTableWidget(self.centralwidget)
        self.tblLISTED.setGeometry(QtCore.QRect(10, 340, 761, 192))
        self.tblLISTED.setObjectName("tblLISTED")
        self.tblLISTED.setColumnCount(0)
        self.tblLISTED.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblID.setText(_translate("MainWindow", "ID"))
        self.lblNAME.setText(_translate("MainWindow", "NAME"))
        self.lblNUMBER.setText(_translate("MainWindow", "NUMBER"))
        self.lblMAIL.setText(_translate("MainWindow", "MAIL"))
        self.lblCITY.setText(_translate("MainWindow", "CITY"))
        self.lblSURNAME.setText(_translate("MainWindow", "SURNAME"))
        self.btnSAVE.setText(_translate("MainWindow", "SAVE"))
        self.btnDELETE.setText(_translate("MainWindow", "DELETE"))
        self.btnUPDATE.setText(_translate("MainWindow", "UPDATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
